# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import users_pb2 as proto_dot_users__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\x12\x12\x64istributed_agenda\x1a\x11proto/users.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"7\n\rSignUpRequest\x12&\n\x04user\x18\x01 \x01(\x0b\x32\x18.distributed_agenda.User\"\x10\n\x0eSignUpResponse2\xa5\x01\n\x04\x41uth\x12L\n\x05Login\x12 .distributed_agenda.LoginRequest\x1a!.distributed_agenda.LoginResponse\x12O\n\x06SignUp\x12!.distributed_agenda.SignUpRequest\x1a\".distributed_agenda.SignUpResponseB\x10Z\x0e./server/protob\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_SIGNUPREQUEST = DESCRIPTOR.message_types_by_name['SignUpRequest']
_SIGNUPRESPONSE = DESCRIPTOR.message_types_by_name['SignUpResponse']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'proto.auth_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'proto.auth_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

SignUpRequest = _reflection.GeneratedProtocolMessageType('SignUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPREQUEST,
  '__module__' : 'proto.auth_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.SignUpRequest)
  })
_sym_db.RegisterMessage(SignUpRequest)

SignUpResponse = _reflection.GeneratedProtocolMessageType('SignUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPRESPONSE,
  '__module__' : 'proto.auth_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.SignUpResponse)
  })
_sym_db.RegisterMessage(SignUpResponse)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016./server/proto'
  _LOGINREQUEST._serialized_start=59
  _LOGINREQUEST._serialized_end=109
  _LOGINRESPONSE._serialized_start=111
  _LOGINRESPONSE._serialized_end=141
  _SIGNUPREQUEST._serialized_start=143
  _SIGNUPREQUEST._serialized_end=198
  _SIGNUPRESPONSE._serialized_start=200
  _SIGNUPRESPONSE._serialized_end=216
  _AUTH._serialized_start=219
  _AUTH._serialized_end=384
# @@protoc_insertion_point(module_scope)
