# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/history.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import users_pb2 as proto_dot_users__pb2
from proto import groups_pb2 as proto_dot_groups__pb2
from proto import events_pb2 as proto_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/history.proto\x12\x12\x64istributed_agenda\x1a\x11proto/users.proto\x1a\x12proto/groups.proto\x1a\x12proto/events.proto\"\xc6\x01\n\x0cHistoryEntry\x12*\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1a.distributed_agenda.Action\x12(\n\x04user\x18\x02 \x01(\x0b\x32\x18.distributed_agenda.UserH\x00\x12*\n\x05group\x18\x03 \x01(\x0b\x32\x19.distributed_agenda.GroupH\x00\x12*\n\x05\x65vent\x18\x04 \x01(\x0b\x32\x19.distributed_agenda.EventH\x00\x42\x08\n\x06target\"<\n\x07History\x12\x31\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .distributed_agenda.HistoryEntry\"X\n\x16\x41\x64\x64HistoryEntryRequest\x12/\n\x05\x65ntry\x18\x01 \x01(\x0b\x32 .distributed_agenda.HistoryEntry\x12\r\n\x05users\x18\x02 \x03(\t\"\x19\n\x17\x41\x64\x64HistoryEntryResponse\")\n\x15GetFullHistoryRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"I\n\x16GetFullHistoryResponse\x12/\n\x05\x65ntry\x18\x01 \x01(\x0b\x32 .distributed_agenda.HistoryEntry\"?\n\x1bGetHistoryFromOffsetRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"O\n\x1cGetHistoryFromOffsetResponse\x12/\n\x05\x65ntry\x18\x01 \x01(\x0b\x32 .distributed_agenda.HistoryEntry*[\n\x06\x41\x63tion\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\n\n\x06JOINED\x10\x03\x12\x08\n\x04LEFT\x10\x04\x12\x0b\n\x07\x43ONFIRM\x10\x05\x12\n\n\x06REJECT\x10\x06\x32\xea\x02\n\x0eHistoryService\x12l\n\x0f\x41\x64\x64HistoryEntry\x12*.distributed_agenda.AddHistoryEntryRequest\x1a+.distributed_agenda.AddHistoryEntryResponse\"\x00\x12k\n\x0eGetFullHistory\x12).distributed_agenda.GetFullHistoryRequest\x1a*.distributed_agenda.GetFullHistoryResponse\"\x00\x30\x01\x12}\n\x14GetHistoryFromOffset\x12/.distributed_agenda.GetHistoryFromOffsetRequest\x1a\x30.distributed_agenda.GetHistoryFromOffsetResponse\"\x00\x30\x01\x42\x10Z\x0e./server/protob\x06proto3')

_ACTION = DESCRIPTOR.enum_types_by_name['Action']
Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
CREATE = 0
UPDATE = 1
DELETE = 2
JOINED = 3
LEFT = 4
CONFIRM = 5
REJECT = 6


_HISTORYENTRY = DESCRIPTOR.message_types_by_name['HistoryEntry']
_HISTORY = DESCRIPTOR.message_types_by_name['History']
_ADDHISTORYENTRYREQUEST = DESCRIPTOR.message_types_by_name['AddHistoryEntryRequest']
_ADDHISTORYENTRYRESPONSE = DESCRIPTOR.message_types_by_name['AddHistoryEntryResponse']
_GETFULLHISTORYREQUEST = DESCRIPTOR.message_types_by_name['GetFullHistoryRequest']
_GETFULLHISTORYRESPONSE = DESCRIPTOR.message_types_by_name['GetFullHistoryResponse']
_GETHISTORYFROMOFFSETREQUEST = DESCRIPTOR.message_types_by_name['GetHistoryFromOffsetRequest']
_GETHISTORYFROMOFFSETRESPONSE = DESCRIPTOR.message_types_by_name['GetHistoryFromOffsetResponse']
HistoryEntry = _reflection.GeneratedProtocolMessageType('HistoryEntry', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYENTRY,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.HistoryEntry)
  })
_sym_db.RegisterMessage(HistoryEntry)

History = _reflection.GeneratedProtocolMessageType('History', (_message.Message,), {
  'DESCRIPTOR' : _HISTORY,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.History)
  })
_sym_db.RegisterMessage(History)

AddHistoryEntryRequest = _reflection.GeneratedProtocolMessageType('AddHistoryEntryRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDHISTORYENTRYREQUEST,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.AddHistoryEntryRequest)
  })
_sym_db.RegisterMessage(AddHistoryEntryRequest)

AddHistoryEntryResponse = _reflection.GeneratedProtocolMessageType('AddHistoryEntryResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDHISTORYENTRYRESPONSE,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.AddHistoryEntryResponse)
  })
_sym_db.RegisterMessage(AddHistoryEntryResponse)

GetFullHistoryRequest = _reflection.GeneratedProtocolMessageType('GetFullHistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFULLHISTORYREQUEST,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.GetFullHistoryRequest)
  })
_sym_db.RegisterMessage(GetFullHistoryRequest)

GetFullHistoryResponse = _reflection.GeneratedProtocolMessageType('GetFullHistoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFULLHISTORYRESPONSE,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.GetFullHistoryResponse)
  })
_sym_db.RegisterMessage(GetFullHistoryResponse)

GetHistoryFromOffsetRequest = _reflection.GeneratedProtocolMessageType('GetHistoryFromOffsetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETHISTORYFROMOFFSETREQUEST,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.GetHistoryFromOffsetRequest)
  })
_sym_db.RegisterMessage(GetHistoryFromOffsetRequest)

GetHistoryFromOffsetResponse = _reflection.GeneratedProtocolMessageType('GetHistoryFromOffsetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETHISTORYFROMOFFSETRESPONSE,
  '__module__' : 'proto.history_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.GetHistoryFromOffsetResponse)
  })
_sym_db.RegisterMessage(GetHistoryFromOffsetResponse)

_HISTORYSERVICE = DESCRIPTOR.services_by_name['HistoryService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016./server/proto'
  _ACTION._serialized_start=746
  _ACTION._serialized_end=837
  _HISTORYENTRY._serialized_start=103
  _HISTORYENTRY._serialized_end=301
  _HISTORY._serialized_start=303
  _HISTORY._serialized_end=363
  _ADDHISTORYENTRYREQUEST._serialized_start=365
  _ADDHISTORYENTRYREQUEST._serialized_end=453
  _ADDHISTORYENTRYRESPONSE._serialized_start=455
  _ADDHISTORYENTRYRESPONSE._serialized_end=480
  _GETFULLHISTORYREQUEST._serialized_start=482
  _GETFULLHISTORYREQUEST._serialized_end=523
  _GETFULLHISTORYRESPONSE._serialized_start=525
  _GETFULLHISTORYRESPONSE._serialized_end=598
  _GETHISTORYFROMOFFSETREQUEST._serialized_start=600
  _GETHISTORYFROMOFFSETREQUEST._serialized_end=663
  _GETHISTORYFROMOFFSETRESPONSE._serialized_start=665
  _GETHISTORYFROMOFFSETRESPONSE._serialized_end=744
  _HISTORYSERVICE._serialized_start=840
  _HISTORYSERVICE._serialized_end=1202
# @@protoc_insertion_point(module_scope)
