# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/users.proto\x12\x12\x64istributed_agenda\"K\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cpasswordHash\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"9\n\x0f\x45\x64itUserRequest\x12&\n\x04user\x18\x01 \x01(\x0b\x32\x18.distributed_agenda.User\"9\n\x0fGetUserResponse\x12&\n\x04user\x18\x01 \x01(\x0b\x32\x18.distributed_agenda.User\"\x12\n\x10\x45\x64itUserResponse2\xbc\x01\n\x0bUserService\x12T\n\x07GetUser\x12\".distributed_agenda.GetUserRequest\x1a#.distributed_agenda.GetUserResponse\"\x00\x12W\n\x08\x45\x64itUser\x12#.distributed_agenda.EditUserRequest\x1a$.distributed_agenda.EditUserResponse\"\x00\x42\x10Z\x0e./server/protob\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_GETUSERREQUEST = DESCRIPTOR.message_types_by_name['GetUserRequest']
_EDITUSERREQUEST = DESCRIPTOR.message_types_by_name['EditUserRequest']
_GETUSERRESPONSE = DESCRIPTOR.message_types_by_name['GetUserResponse']
_EDITUSERRESPONSE = DESCRIPTOR.message_types_by_name['EditUserResponse']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'proto.users_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.User)
  })
_sym_db.RegisterMessage(User)

GetUserRequest = _reflection.GeneratedProtocolMessageType('GetUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERREQUEST,
  '__module__' : 'proto.users_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.GetUserRequest)
  })
_sym_db.RegisterMessage(GetUserRequest)

EditUserRequest = _reflection.GeneratedProtocolMessageType('EditUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _EDITUSERREQUEST,
  '__module__' : 'proto.users_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.EditUserRequest)
  })
_sym_db.RegisterMessage(EditUserRequest)

GetUserResponse = _reflection.GeneratedProtocolMessageType('GetUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERRESPONSE,
  '__module__' : 'proto.users_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.GetUserResponse)
  })
_sym_db.RegisterMessage(GetUserResponse)

EditUserResponse = _reflection.GeneratedProtocolMessageType('EditUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _EDITUSERRESPONSE,
  '__module__' : 'proto.users_pb2'
  # @@protoc_insertion_point(class_scope:distributed_agenda.EditUserResponse)
  })
_sym_db.RegisterMessage(EditUserResponse)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016./server/proto'
  _USER._serialized_start=41
  _USER._serialized_end=116
  _GETUSERREQUEST._serialized_start=118
  _GETUSERREQUEST._serialized_end=152
  _EDITUSERREQUEST._serialized_start=154
  _EDITUSERREQUEST._serialized_end=211
  _GETUSERRESPONSE._serialized_start=213
  _GETUSERRESPONSE._serialized_end=270
  _EDITUSERRESPONSE._serialized_start=272
  _EDITUSERRESPONSE._serialized_end=290
  _USERSERVICE._serialized_start=293
  _USERSERVICE._serialized_end=481
# @@protoc_insertion_point(module_scope)
