"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERNAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PASSWORDHASH_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    username: typing.Text
    name: typing.Text
    passwordHash: typing.Text
    email: typing.Text
    def __init__(self,
        *,
        username: typing.Text = ...,
        name: typing.Text = ...,
        passwordHash: typing.Text = ...,
        email: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email",b"email","name",b"name","passwordHash",b"passwordHash","username",b"username"]) -> None: ...
global___User = User

class GetUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERNAME_FIELD_NUMBER: builtins.int
    username: typing.Text
    def __init__(self,
        *,
        username: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["username",b"username"]) -> None: ...
global___GetUserRequest = GetUserRequest

class EditUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    def __init__(self,
        *,
        user: typing.Optional[global___User] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["user",b"user"]) -> None: ...
global___EditUserRequest = EditUserRequest

class GetUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    def __init__(self,
        *,
        user: typing.Optional[global___User] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["user",b"user"]) -> None: ...
global___GetUserResponse = GetUserResponse

class EditUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___EditUserResponse = EditUserResponse
