// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: proto/history.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_CREATE  Action = 0
	Action_UPDATE  Action = 1
	Action_DELETE  Action = 2
	Action_JOINED  Action = 3
	Action_LEFT    Action = 4
	Action_CONFIRM Action = 5
	Action_REJECT  Action = 6
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "JOINED",
		4: "LEFT",
		5: "CONFIRM",
		6: "REJECT",
	}
	Action_value = map[string]int32{
		"CREATE":  0,
		"UPDATE":  1,
		"DELETE":  2,
		"JOINED":  3,
		"LEFT":    4,
		"CONFIRM": 5,
		"REJECT":  6,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_history_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_history_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{0}
}

type HistoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Action `protobuf:"varint,1,opt,name=action,proto3,enum=distributed_agenda.Action" json:"action,omitempty"`
	// Types that are assignable to Target:
	//	*HistoryEntry_User
	//	*HistoryEntry_Group
	//	*HistoryEntry_Event
	Target isHistoryEntry_Target `protobuf_oneof:"target"`
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryEntry) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_CREATE
}

func (m *HistoryEntry) GetTarget() isHistoryEntry_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (x *HistoryEntry) GetUser() *User {
	if x, ok := x.GetTarget().(*HistoryEntry_User); ok {
		return x.User
	}
	return nil
}

func (x *HistoryEntry) GetGroup() *Group {
	if x, ok := x.GetTarget().(*HistoryEntry_Group); ok {
		return x.Group
	}
	return nil
}

func (x *HistoryEntry) GetEvent() *Event {
	if x, ok := x.GetTarget().(*HistoryEntry_Event); ok {
		return x.Event
	}
	return nil
}

type isHistoryEntry_Target interface {
	isHistoryEntry_Target()
}

type HistoryEntry_User struct {
	User *User `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
}

type HistoryEntry_Group struct {
	Group *Group `protobuf:"bytes,3,opt,name=group,proto3,oneof"`
}

type HistoryEntry_Event struct {
	Event *Event `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

func (*HistoryEntry_User) isHistoryEntry_Target() {}

func (*HistoryEntry_Group) isHistoryEntry_Target() {}

func (*HistoryEntry_Event) isHistoryEntry_Target() {}

type History struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*HistoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *History) Reset() {
	*x = History{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{1}
}

func (x *History) GetEntries() []*HistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AddHistoryEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *HistoryEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Users []string      `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *AddHistoryEntryRequest) Reset() {
	*x = AddHistoryEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHistoryEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHistoryEntryRequest) ProtoMessage() {}

func (x *AddHistoryEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHistoryEntryRequest.ProtoReflect.Descriptor instead.
func (*AddHistoryEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{2}
}

func (x *AddHistoryEntryRequest) GetEntry() *HistoryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *AddHistoryEntryRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddHistoryEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddHistoryEntryResponse) Reset() {
	*x = AddHistoryEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHistoryEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHistoryEntryResponse) ProtoMessage() {}

func (x *AddHistoryEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHistoryEntryResponse.ProtoReflect.Descriptor instead.
func (*AddHistoryEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{3}
}

type GetFullHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetFullHistoryRequest) Reset() {
	*x = GetFullHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullHistoryRequest) ProtoMessage() {}

func (x *GetFullHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetFullHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{4}
}

func (x *GetFullHistoryRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetFullHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *HistoryEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *GetFullHistoryResponse) Reset() {
	*x = GetFullHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFullHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullHistoryResponse) ProtoMessage() {}

func (x *GetFullHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetFullHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{5}
}

func (x *GetFullHistoryResponse) GetEntry() *HistoryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetHistoryFromOffsetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Offset   int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetHistoryFromOffsetRequest) Reset() {
	*x = GetHistoryFromOffsetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryFromOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryFromOffsetRequest) ProtoMessage() {}

func (x *GetHistoryFromOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryFromOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryFromOffsetRequest) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryFromOffsetRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetHistoryFromOffsetRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetHistoryFromOffsetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *HistoryEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *GetHistoryFromOffsetResponse) Reset() {
	*x = GetHistoryFromOffsetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_history_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryFromOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryFromOffsetResponse) ProtoMessage() {}

func (x *GetHistoryFromOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_history_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryFromOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryFromOffsetResponse) Descriptor() ([]byte, []int) {
	return file_proto_history_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryFromOffsetResponse) GetEntry() *HistoryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_proto_history_proto protoreflect.FileDescriptor

var file_proto_history_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x01, 0x0a, 0x0c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x48, 0x00, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x31, 0x0a, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42,
	0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x45, 0x0a, 0x07, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x3a, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x22, 0x66, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46,
	0x75, 0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x51, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x56, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x46, 0x72, 0x6f, 0x6d, 0x4f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64,
	0x61, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x2a, 0x5b, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4a, 0x4f, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x52, 0x4d, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54,
	0x10, 0x06, 0x32, 0xea, 0x02, 0x0a, 0x0e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6c, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2a, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x41, 0x64,
	0x64, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x41, 0x64, 0x64, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75,
	0x6c, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2a, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x7d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x46, 0x72,
	0x6f, 0x6d, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x2f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_history_proto_rawDescOnce sync.Once
	file_proto_history_proto_rawDescData = file_proto_history_proto_rawDesc
)

func file_proto_history_proto_rawDescGZIP() []byte {
	file_proto_history_proto_rawDescOnce.Do(func() {
		file_proto_history_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_history_proto_rawDescData)
	})
	return file_proto_history_proto_rawDescData
}

var file_proto_history_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_history_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_history_proto_goTypes = []interface{}{
	(Action)(0),                          // 0: distributed_agenda.Action
	(*HistoryEntry)(nil),                 // 1: distributed_agenda.HistoryEntry
	(*History)(nil),                      // 2: distributed_agenda.History
	(*AddHistoryEntryRequest)(nil),       // 3: distributed_agenda.AddHistoryEntryRequest
	(*AddHistoryEntryResponse)(nil),      // 4: distributed_agenda.AddHistoryEntryResponse
	(*GetFullHistoryRequest)(nil),        // 5: distributed_agenda.GetFullHistoryRequest
	(*GetFullHistoryResponse)(nil),       // 6: distributed_agenda.GetFullHistoryResponse
	(*GetHistoryFromOffsetRequest)(nil),  // 7: distributed_agenda.GetHistoryFromOffsetRequest
	(*GetHistoryFromOffsetResponse)(nil), // 8: distributed_agenda.GetHistoryFromOffsetResponse
	(*User)(nil),                         // 9: distributed_agenda.User
	(*Group)(nil),                        // 10: distributed_agenda.Group
	(*Event)(nil),                        // 11: distributed_agenda.Event
}
var file_proto_history_proto_depIdxs = []int32{
	0,  // 0: distributed_agenda.HistoryEntry.action:type_name -> distributed_agenda.Action
	9,  // 1: distributed_agenda.HistoryEntry.user:type_name -> distributed_agenda.User
	10, // 2: distributed_agenda.HistoryEntry.group:type_name -> distributed_agenda.Group
	11, // 3: distributed_agenda.HistoryEntry.event:type_name -> distributed_agenda.Event
	1,  // 4: distributed_agenda.History.entries:type_name -> distributed_agenda.HistoryEntry
	1,  // 5: distributed_agenda.AddHistoryEntryRequest.entry:type_name -> distributed_agenda.HistoryEntry
	1,  // 6: distributed_agenda.GetFullHistoryResponse.entry:type_name -> distributed_agenda.HistoryEntry
	1,  // 7: distributed_agenda.GetHistoryFromOffsetResponse.entry:type_name -> distributed_agenda.HistoryEntry
	3,  // 8: distributed_agenda.HistoryService.AddHistoryEntry:input_type -> distributed_agenda.AddHistoryEntryRequest
	5,  // 9: distributed_agenda.HistoryService.GetFullHistory:input_type -> distributed_agenda.GetFullHistoryRequest
	7,  // 10: distributed_agenda.HistoryService.GetHistoryFromOffset:input_type -> distributed_agenda.GetHistoryFromOffsetRequest
	4,  // 11: distributed_agenda.HistoryService.AddHistoryEntry:output_type -> distributed_agenda.AddHistoryEntryResponse
	6,  // 12: distributed_agenda.HistoryService.GetFullHistory:output_type -> distributed_agenda.GetFullHistoryResponse
	8,  // 13: distributed_agenda.HistoryService.GetHistoryFromOffset:output_type -> distributed_agenda.GetHistoryFromOffsetResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_history_proto_init() }
func file_proto_history_proto_init() {
	if File_proto_history_proto != nil {
		return
	}
	file_proto_users_proto_init()
	file_proto_groups_proto_init()
	file_proto_events_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_history_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*History); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHistoryEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHistoryEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFullHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFullHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryFromOffsetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_history_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryFromOffsetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_history_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*HistoryEntry_User)(nil),
		(*HistoryEntry_Group)(nil),
		(*HistoryEntry_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_history_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_history_proto_goTypes,
		DependencyIndexes: file_proto_history_proto_depIdxs,
		EnumInfos:         file_proto_history_proto_enumTypes,
		MessageInfos:      file_proto_history_proto_msgTypes,
	}.Build()
	File_proto_history_proto = out.File
	file_proto_history_proto_rawDesc = nil
	file_proto_history_proto_goTypes = nil
	file_proto_history_proto_depIdxs = nil
}
